"""added password column

Revision ID: b43ef8af122e
Revises: 
Create Date: 2026-02-12 12:22:07.285561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b43ef8af122e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('love_page',
    sa.Column('id', sa.String(length=8), nullable=False),
    sa.Column('your_name', sa.String(length=100), nullable=True),
    sa.Column('partner_name', sa.String(length=100), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('your_photo', sa.String(length=200), nullable=True),
    sa.Column('partner_photo', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('plan', sa.String(length=20), nullable=True),
    sa.Column('password', sa.String(length=100), nullable=True),
    sa.Column('theme', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('love_page')
    # ### end Alembic commands ###
