"""added views counter

Revision ID: e46b945bc71e
Revises: b43ef8af122e
Create Date: 2026-02-12 21:51:10.850527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e46b945bc71e'
down_revision = 'b43ef8af122e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('love_page', schema=None) as batch_op:
        batch_op.add_column(sa.Column('music', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('views', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('love_page', schema=None) as batch_op:
        batch_op.drop_column('views')
        batch_op.drop_column('music')

    # ### end Alembic commands ###
